// Single source of truth for the version stamp printed in generated reports.
// Kept in sync with package.json + SKILL.md by tests/skill-compliance.test.mjs
// (asserts this constant equals package.json#version).
export const REPORT_VERSION = '0.3.0';

/**
 * Render a ScanResult into a human-readable Markdown report.
 * @param {Object} scanResult - from runHeuristicScan()
 * @param {Object} [options]
 * @param {string} [options.version] - Override the version stamp (default: REPORT_VERSION)
 * @returns {string} Markdown
 */
export function renderScanReport(scanResult, options = {}) {
  const lines = [];
  const { privacyScore, riskLevel, summary, identity, exposures, recommendations, scanId, scannedAt } = scanResult;
  const version = options.version || REPORT_VERSION;

  lines.push('# Privacy Scan Report');
  lines.push('');
  lines.push(`**Scan ID**: ${scanId}`);
  lines.push(`**Scanned**: ${scannedAt}`);
  if (identity?.name) lines.push(`**Identity**: ${identity.name}`);
  lines.push('');

  // Privacy Score
  const scoreBar = renderScoreBar(privacyScore);
  lines.push(`## Privacy Score: ${privacyScore}/100 (${riskLevel.toUpperCase()} RISK)`);
  lines.push('');
  lines.push(scoreBar);
  lines.push('');

  // Exposure Summary
  lines.push('## Exposure Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total brokers scanned | ${summary.totalBrokers} |`);
  lines.push(`| **Likely exposed** | **${summary.likelyExposed}** |`);
  lines.push(`| Possibly exposed | ${summary.possiblyExposed} |`);
  lines.push(`| Unlikely exposed | ${summary.unlikelyExposed} |`);
  lines.push('');

  // Risk Distribution
  lines.push('## Risk Distribution');
  lines.push('');
  lines.push(`| Risk Level | Count |`);
  lines.push(`|------------|-------|`);
  lines.push(`| Critical | ${summary.byRisk.critical} |`);
  lines.push(`| High | ${summary.byRisk.high} |`);
  lines.push(`| Moderate | ${summary.byRisk.moderate} |`);
  lines.push(`| Low | ${summary.byRisk.low} |`);
  lines.push('');

  // By Category
  lines.push('## Exposure by Category');
  lines.push('');
  lines.push('| Category | Likely | Possible | Unlikely |');
  lines.push('|----------|--------|----------|----------|');
  for (const [cat, counts] of Object.entries(summary.byCategory).sort((a, b) => b[1].likely - a[1].likely)) {
    lines.push(`| ${cat} | ${counts.likely} | ${counts.possible} | ${counts.unlikely} |`);
  }
  lines.push('');

  // Recommendations
  if (recommendations.length > 0) {
    lines.push('## Priority Recommendations');
    lines.push('');
    for (const rec of recommendations) {
      const urgency = rec.priority <= 2 ? 'CRITICAL' : rec.priority <= 4 ? 'HIGH' : 'MODERATE';
      lines.push(`${rec.priority}. **[${urgency}]** ${rec.action}`);
    }
    lines.push('');
  }

  // Top Exposed Brokers (likely only, max 30)
  const likelyBrokers = exposures.filter(e => e.likelihood === 'likely').slice(0, 30);
  if (likelyBrokers.length > 0) {
    lines.push('## Top Exposed Brokers');
    lines.push('');
    lines.push('| Broker | Category | Confidence | Risk | Opt-Out | Difficulty |');
    lines.push('|--------|----------|------------|------|---------|------------|');
    for (const exp of likelyBrokers) {
      const url = exp.optOutUrl ? `[link](${exp.optOutUrl})` : 'N/A';
      lines.push(`| ${exp.displayName} | ${exp.category} | ${(exp.confidence * 100).toFixed(0)}% | ${exp.riskTier} | ${url} | ${exp.removalDifficulty} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Vanish Privacy Scanner v${version}*`);

  return lines.join('\n');
}

/**
 * Render a compact JSON summary (for dashboards / API).
 */
export function renderScanSummaryJson(scanResult) {
  return {
    scanId: scanResult.scanId,
    scannedAt: scanResult.scannedAt,
    privacyScore: scanResult.privacyScore,
    riskLevel: scanResult.riskLevel,
    likelyExposed: scanResult.summary.likelyExposed,
    possiblyExposed: scanResult.summary.possiblyExposed,
    totalBrokers: scanResult.summary.totalBrokers,
    topRecommendation: scanResult.recommendations[0]?.action || null
  };
}

function renderScoreBar(score) {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  return `\`[${bar}]\` ${score}/100`;
}
